// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CfEnv {
	readonly AI_GATEWAY: string;
	readonly DATADOG_API_KEY: string;
	readonly DATADOG_ENV: string;
	readonly DATADOG_HOST: string;

	readonly MAILGUN_ENDPOINT: string;
	readonly MAILGUN_KEY: string;

	readonly JIRA_API_KEY: string;
	readonly JIRA_DOMAIN: string;
	readonly JIRA_EMAIL: string;
	readonly JIRA_SYNC_ENABLED: string;
	readonly JIRA_SYNC_TOKEN: string;
	readonly JIRA_SYNC_QUEUE: Queue;
	readonly JIRA_SYNC_URL: string;

	readonly SITE_URL: string;
	readonly KV_BYPASS?: string;
	readonly WORKER_UPSERT_ALLOWED: string;

	readonly EMAIL_ADMIN: string;
	readonly EMAIL_FROM: string;

	readonly EMAIL_SUPRESS: string;

	readonly EMAIL_TEMPLATE_INVITE: string;
	readonly EMAIL_TEMPLATE_PROJECT_ASSIGNED: string;
}
