// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CfEnv {
	readonly AI_GATEWAY: string;
	readonly DATADOG_API_KEY: string;
	readonly DATADOG_ENV: string;
	readonly DATADOG_HOST: string;
	readonly ACCOUNT_ID: string;
	readonly ELEVENLABS_API_KEY: string;
	readonly ELEVENLABS_VOICE: string;
	readonly KV_DATA: KVNamespace;
}
